name: Tests

on:
  push:

jobs:
  install_dependencies:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

  testrun:
    needs: install_dependencies
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Create .env file
        run: |
            touch .env
            echo TOKEN=${{ secrets.TOKEN }} >> .env
            echo CLIENT_ID=${{ secrets.CLIENT_ID }} >> .env
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test script run
        run: |
            pnpm run deploy
            echo $?
            if [ $? -eq 2 ]; then
                pnpm run test
            else
                exit 1
            fi
        continue-on-error: true
